version: "3"
services:
  client:
    image: "itscarlosisaac/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "itscarlosisaac/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    worker:
      image: "itscarlosisaac/multi-worker"
      mem_limit: 128m
      hostname: worker
      environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:
      image: "itscarlosisaac/multi-nginx"
      mem_limit: 128m
      hostname: nginx
      ports:
        - "80:80"